#!/usr/bin/env node
/**
 * Generate CATALOG.md from block metadata.
 * Usage: node scripts/gen-catalog.js
 */
import { readdir, readFile, writeFile } from 'fs/promises';
import { join, relative, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

async function findBlocks(dir) {
  const blocks = [];
  const entries = await readdir(dir, { withFileTypes: true, recursive: true });
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith('.js') && entry.name !== 'index.js') {
      const fullPath = join(entry.parentPath || entry.path, entry.name);
      const content = await readFile(fullPath, 'utf-8');

      // Extract block metadata from source
      const nameMatch = content.match(/name:\s*['"]([^'"]+)['"]/);
      const descMatch = content.match(/description:\s*['"]([^'"]+)['"]/);
      const tagsMatch = content.match(/tags:\s*\[([^\]]+)\]/);
      const exampleMatch = content.match(/example:\s*`([^`]+)`/);

      // Extract exported function name
      const fnMatch = content.match(/export function (\w+)/);

      if (nameMatch) {
        const relPath = relative(dir, fullPath);
        const category = dirname(relPath);
        blocks.push({
          name: nameMatch[1],
          description: descMatch?.[1] || '',
          tags: tagsMatch?.[1]?.replace(/['"]/g, '').split(',').map(t => t.trim()) || [],
          example: exampleMatch?.[1] || '',
          fn: fnMatch?.[1] || '',
          category,
          path: relPath,
        });
      }
    }
  }
  return blocks;
}

function generateMarkdown(title, blocks) {
  let md = `# ${title}\n\n`;
  md += `> Auto-generated by \`npm run catalog\`. Do not edit manually.\n\n`;
  md += `${blocks.length} blocks available.\n\n`;

  // Group by category
  const categories = {};
  for (const b of blocks) {
    (categories[b.category] ??= []).push(b);
  }

  for (const [cat, catBlocks] of Object.entries(categories).sort()) {
    md += `## ${cat}\n\n`;
    for (const b of catBlocks) {
      md += `### ${b.name}\n`;
      md += `${b.description}\n`;
      md += `Tags: ${b.tags.join(', ')}\n`;
      if (b.fn) md += `Function: \`${b.fn}()\`\n`;
      if (b.example) md += `\`\`\`js\n${b.example}\n\`\`\`\n`;
      md += '\n';
    }
  }

  return md;
}

async function main() {
  const pipelines = [
    { dir: join(root, 'src/sound/blocks'), title: 'Sound Blocks' },
    { dir: join(root, 'src/sprites/blocks'), title: 'Sprite Blocks' },
  ];

  for (const { dir, title } of pipelines) {
    try {
      const blocks = await findBlocks(dir);
      if (blocks.length === 0) {
        console.log(`No blocks found in ${dir}`);
        continue;
      }
      const md = generateMarkdown(title, blocks);
      const outPath = join(dir, 'CATALOG.md');
      await writeFile(outPath, md);
      console.log(`${title}: ${blocks.length} blocks → ${outPath}`);
    } catch (e) {
      if (e.code === 'ENOENT') {
        console.log(`Skipping ${dir} (not found)`);
      } else {
        throw e;
      }
    }
  }
}

main();
